### ISSUE TITLE
from vi.ui import viui, systemtray -> ImportError: No module named requests

### ISSUE THREAD

**Issue by Tetractys** [XanthosX/vintel#133]
Hi!
I would like to know which lib i missed to install (i'm on a fresh LMint 18 installation)
this is the output:

```
davide@thor-p ~/bin/vintel/src $ python ./vintel.py 
Traceback (most recent call last):
  File "vintel.py", line 31, in <module>
    from vi.ui import viui, systemtray
  File "/home/davide/bin/vintel/src/vi/ui/viui.py", line 24, in <module>
    import requests
ImportError: No module named requests

```

Thanks a lot for any suggestion!

**Comment by Xanthos-Code** [comment]
Requests

**Comment by Tetractys** [comment]
Thanks. Got it.
