### ISSUE TITLE
EVE On Mac with Wine

### ISSUE THREAD

**Issue by jeffmilton** [XanthosX/vintel#134]
My chat logs no longer seem to be stored in the usual place
Library/Application Support/EVE Online/p_drive/User/My Documents/EVE/logs

When using the client with Wine on my mac - they are in ~/Documents/EVE/logs/Chatlogs

We need the option to be able to switch the log location.

**Comment by Xanthos-Code** [comment]
It should failover to the new location.

**Comment by jeffmilton** [comment]
I agree! It doesn't fail over to the new location, it simply gives you this prompt:
http://imgur.com/JBzhr9K

So the only option is to quit the program.

**Comment by jeffmilton** [comment]
I'm currently using 1.2.3, which appears to be the latest version.

**Comment by ppfeufer** [comment]
start with "python pyfa.py /absolute/path/to/your/logfiles"
Should do the trick

**Comment by henrikfrandsen** [comment]
but it did not:

> > Henriks-iMac:Chatlogs henrikvfrandsen$ pwd
> > /Users/henrikvfrandsen/Documents/EVE/logs/Chatlogs
> > Henriks-iMac:Chatlogs henrikvfrandsen$ python pyfa.py /Users/henrikvfrandsen/Documents/EVE/logs/Chatlogs
> > python: can't open file 'pyfa.py': [Errno 2] No such file or directory
> > Henriks-iMac:Chatlogs henrikvfrandsen$ 
> > <<
> > what did i do wrong?

**Comment by Xanthos-Code** [comment]
this is vintel not pyfa

**Comment by henrikfrandsen** [comment]
Still doesn't do the trick hope this vine issue vil be fixed in version 1.2.4 :): 

> Henriks-iMac:MacOS henrikvfrandsen$ python vintel-1.2.3 /Users/henrikvfrandsen/Documents/EVE/logs/Chatlogs/
>   File "vintel-1.2.3", line 1
> SyntaxError: Non-ASCII character '\xcf' in file vintel-1.2.3 on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> Henriks-iMac:MacOS henrikvfrandsen$ cd vintel-1.2.3

**Comment by spemmons** [comment]
I get "vintel-1.2.3" quit unexpectedly on my Mac Book Pro 10.10.5 right after running the app every time.

The popup has lots of low-level crash details, but the following seemed relevant:

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

It looks like there is a Python memory fault. Just in case, here is what Python says on the console.

Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin

Any suggestions?

Thanks!

**Comment by spemmons** [comment]
I was able to solve my problem by running "pip install requests" -- this was something missing from my system that I discovered when I tried to run the source code.

**Comment by spemmons** [comment]
I had to go back to "vintel-1.2.2" to get it to work from source by executing python with my chatlog directory as a parameter.

**Comment by Coroc** [comment]
Hi. I have troubles with Vintel for mac. "Vintel was closed unexpectedly" is the message i have. When i try to run it from python i have this error "Traceback (most recent call last):
  File "/Applications/vintel-1.2.3/src/vintel.py", line 29, in <module>
    from PyQt4 import QtGui
ImportError: No module named PyQt4
How can i resolve it." 
Thank you

**Comment by henrikfrandsen** [comment]
I have givent up on vintel, i guess If your a programmer and install all
the help packages you should Be able to run it from source and change the
path in one of the files. I located the file but is shit at programming and
installing programs that runs in x-11 or terminal. I have tried to get help
from forum before, but the answer was unpulite and not noob friendly I hope
the vine support will be out there in the next version but until then I
flying blind.

lør. 31. dec. 2016 kl. 19.24 skrev Coroc <notifications@github.com>:

**Comment by EomarD** [comment]
I finally got Vintel to work on Mac despite the changed folder locations.

Workaround:
Installed "Sync Folders" (App store, Free) and set up a real-time sync of the folder where Eve now writes log files, with the old folder location Vintel expects to find. Confirmed working.

**Comment by henrikfrandsen** [comment]
Can you plz post one 2 locations you put in sync folder for some reason i can’t find my old log files hence dont know where vintel looks? the files are currently stored in by vine /Users/henrikvfrandsen/Documents/EVE/logs/Chatlogs

br. henrik

**Comment by EomarD** [comment]
Old path seems to have been:

/Users/henrikvfrandsen/Library/Application Support/Eve Online/p_drive/User/My Documents/Eve/logs/Chatlogs

**Comment by SorinOrii** [comment]
Confirming latest version does not know the path of the logfiles. Suggest perhaps a dialogue to enter a path if logfiles are not found?
