### ISSUE TITLE
Ubuntu-mate 16.10 - QtWebKit error

### ISSUE THREAD

**Issue by Tetractys** [XanthosX/vintel#139]
Vintel 1.2.3 reports:

```
davide@thor ~/bin/vintel/src $ python ./vintel.py
Traceback (most recent call last):
  File "./vintel.py", line 31, in <module>
    from vi.ui import viui, systemtray
  File "/home/davide/bin/vintel/src/vi/ui/viui.py", line 34, in <module>
    from PyQt4.QtWebKit import QWebPage
ImportError: No module named QtWebKit

```

Although this issue is not new (#90, #104 ...) I ask if I can try to test the new 2.0.0 (QT5) even if not released or if You had solved with some workaround.
Let me know :)

**Comment by eNTi** [comment]
I just got this same error on manjaro after rebuilding qtwebkit-2.3.4-5 from AUR.

**Comment by getoma** [comment]
Same error here on Arch linux.
qtwebkit support for qt4 was phased out on this distribution: [https://www.archlinux.org/todo/phasing-out-qtwebkit/](https://www.archlinux.org/todo/phasing-out-qtwebkit/)
